highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://jina-kim.github.io/
author: Jina Kim

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Jina Kim
name: Jina Kim
email: jinakim@g.skku.edu
email_full: mailto:jinakim@g.skku.edu
website: github.io
website_full: https://jina-kim.github.io/
github: https://github.com/Jina-Kim/
linkedin: https://www.linkedin.com/in/jina-kim-5796a6134
google_scholar: https://scholar.google.com/citations?user=3mpOz-MAAAAJ&hl=en&oi=sra/
twitter: twitter
# needed for travis-ci build
exclude: [vendor]
